#!/bin/bash
# Generated by scripts/install/build-installer.mjs; edit its sources.
# Standalone bootstrap template; build-installer.mjs appends the Python owner.
set -euo pipefail
umask 077
output=human
previous=''
for option in "$@"; do
  if [[ "$previous" == --output ]]; then output="$option"; fi
  if [[ "$option" == --output=json ]]; then output=json; fi
  previous="$option"
done
for option in "$@"; do
  if [[ "$option" == --help || "$option" == -h ]]; then
    if [[ "$output" == json ]]; then
      printf '{"status":"help","usage":"sudo bash install.sh [--version TAG] [--output human|json] [--verbose]","requiredWithoutTerminal":["--public-origin URL","--host-public-addresses COMPLETE_LIST"],"advanced":["--gateway-port PORT","--user-data-root PATH","--user-data-mount PATH"]}\n'
      exit 0
    fi
    cat <<'HELP'
Install dsh-phalanx on Ubuntu 24.04 LTS amd64:
  sudo bash install.sh [--version latest|v0.1.0|v0.1.1|v0.1.1-rc.N]
                      [--bundle-dir verified-private-candidate-directory]
                      [--model-key-file protected-file] [--model-base-url URL]
                      [--host-public-addresses complete-public-IPv4-list]
                      [--listen-address ADDRESS] [--port PORT] [--gateway-port PORT]
                      [--public-origin URL] [--output human|json] [--verbose]
First installation prompts for deployment facts when a terminal is available.
Reinstallation preserves protected configuration and all user data.
HELP
    exit 0
  fi
done
fail() {
  echo "Installation failed: $1" >&2
  diagnostic_json=null
  if [[ -n "${bootstrap_log:-}" ]]; then diagnostic_json="\"$bootstrap_log\""; fi
  if [[ "$output" == json ]]; then printf '{"status":"failed","phase":"Bootstrap","reason":"%s","diagnosticLog":%s}\n' "$1" "${diagnostic_json:-null}"; fi
  exit 1
}
if [[ "$(uname -s)" != Linux || "$(uname -m)" != x86_64 ]]; then
  fail 'Installation supports only Ubuntu 24.04 LTS amd64'
fi
if [[ "$EUID" != 0 ]]; then
  fail 'Run the installer with sudo'
fi
source /etc/os-release
if [[ "$ID" != ubuntu || "$VERSION_ID" != 24.04 ]]; then
  fail 'Installation supports only Ubuntu 24.04 LTS amd64'
fi
if ! command -v python3 >/dev/null || [[ ! -f /etc/ssl/certs/ca-certificates.crt ]]; then
  for path in /var /var/log /var/log/dsh-phalanx; do
    [[ ! -L "$path" ]] || fail 'Diagnostic paths must not be symbolic links'
  done
  mkdir -p /var/log/dsh-phalanx && chmod 700 /var/log/dsh-phalanx || fail 'Cannot create private diagnostics; check disk space'
  bootstrap_log="/var/log/dsh-phalanx/$(date -u +%Y%m%dT%H%M%S)-$$-bootstrap.jsonl"
  (set -o noclobber; : > "$bootstrap_log") || fail 'Cannot create private bootstrap diagnostics'
  bootstrap_event() {
    printf '[Python prerequisites] %s · %ss: %s\n' "$1" "$SECONDS" "$2" >&2
    printf '{"phase":"Python prerequisites","status":"%s","elapsed":%s,"message":"%s"}\n' "$1" "$SECONDS" "$2" >> "$bootstrap_log"
  }
  bootstrap_pid=''
  cleanup_bootstrap() {
    if [[ -n "$bootstrap_pid" ]]; then kill -TERM "$bootstrap_pid" 2>/dev/null || true; wait "$bootstrap_pid" 2>/dev/null || true; fi
  }
  trap cleanup_bootstrap EXIT
  trap 'bootstrap_event failed "Interrupted"; fail "Prerequisite preparation interrupted"' INT TERM
  bootstrap_run() {
    bootstrap_event running 'Preparing Python and certificate prerequisites; raw output withheld until safe diagnostics are available'
    "$@" >/dev/null 2>&1 & bootstrap_pid=$!
    while kill -0 "$bootstrap_pid" 2>/dev/null; do
      bootstrap_event running 'Waiting for prerequisite package manager; check its lock if this continues'
      sleep 3
    done
    if wait "$bootstrap_pid"; then bootstrap_pid=''; bootstrap_event completed 'Prerequisite package command completed';
    else
      status=$?; bootstrap_pid=''; bootstrap_event failed "Package command exited $status"
      echo "Diagnostic log: $bootstrap_log" >&2
      echo 'Inspect prerequisites with sudo apt-get update, then retry sudo bash install.sh.' >&2
      fail 'Unable to prepare Python prerequisites; see the package exit status'
    fi
  }
  bootstrap_run apt-get -o DPkg::Lock::Timeout=600 update
  bootstrap_run env DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=600 install -y --no-install-recommends python3 ca-certificates
  trap - EXIT INT TERM
fi
python3 - "$@" <<'DSH_PHALANX_INSTALLER_PYTHON'
"""Deployment facts and read-only checks before large downloads or host changes."""
import ipaddress
import json
import re
from pathlib import Path
import secrets
import shlex
import urllib.parse

CONFIG = '/etc/dsh-phalanx/environment'
STATE = '/etc/dsh-phalanx/install-state.json'
HOME_DIR = '/var/lib/dsh-phalanx'


class ConfigurationError(ValueError):
    pass


OPTIONS = {
    'model_base_url': 'MODEL_UPSTREAM_BASE_URL', 'model_provider': 'ALLOWED_MODEL_PROVIDER',
    'model': 'ALLOWED_MODEL', 'listen_address': 'HOST', 'port': 'PORT',
    'gateway_port': 'CONTAINER_GATEWAY_PORT', 'public_origin': 'PUBLIC_ORIGIN',
    'host_public_addresses': 'HOST_PUBLIC_ADDRESSES', 'user_data_root': 'USER_DATA_ROOT',
    'user_data_mount': 'USER_DATA_MOUNT',
}


def installed_state(host):
    path = host.path(STATE)
    if path.is_symlink():
        raise ConfigurationError('Installation receipt must not be a symbolic link')
    if not path.exists():
        return None
    state = json.loads(path.read_text())
    if state.get('status') != 'installed':
        return None
    if not host.path('/opt/dsh-phalanx/current').is_symlink() or not host.path(CONFIG).is_file():
        raise ConfigurationError('Successful installation receipt has missing managed files; inspect the existing installation')
    return state


def read_configuration(host):
    path = host.path(CONFIG)
    if not path.exists() and host.path('/etc/dsh-phalanx/install-draft').exists():
        path = host.path('/etc/dsh-phalanx/install-draft')
    if path.is_symlink():
        raise ConfigurationError('Managed configuration must not be a symbolic link')
    values = {}
    if path.exists():
        for line in path.read_text().splitlines():
            key, value = line.split('=', 1)
            parts = shlex.split(value)
            if len(parts) != 1:
                raise ConfigurationError('Invalid protected configuration')
            values[key] = parts[0]
    return values


def validate_authority(url):
    hostname = url.hostname
    if not hostname or '%' in hostname or '\\' in url.netloc:
        raise ConfigurationError('URL must have a valid host')
    if ':' in hostname:
        ipaddress.IPv6Address(hostname)
    else:
        ascii_host = hostname.encode('idna').decode('ascii')
        if not re.fullmatch(r'[A-Za-z0-9_.-]+', ascii_host):
            raise ConfigurationError('URL must have a valid host')
    _ = url.port


def validate_configuration(host, values):
    for name in ('ALLOWED_MODEL_PROVIDER', 'ALLOWED_MODEL', 'MODEL_UPSTREAM_BASE_URL', 'SESSION_SECRET'):
        if not values.get('DSH_PHALANX_'+name, '').strip():
            raise ConfigurationError(name+' must not be empty')
    if values['DSH_PHALANX_ALLOWED_MODEL_PROVIDER'] != 'deepseek-official':
        raise ConfigurationError('Initial legacy model provider must be deepseek-official; configure shared providers in administration after signup')
    if len(values['DSH_PHALANX_SESSION_SECRET']) < 32:
        raise ConfigurationError('Session secret must contain at least 32 characters')
    for address in filter(None, values['DSH_PHALANX_HOST_PUBLIC_ADDRESSES'].split(',')):
        if not ipaddress.IPv4Address(address.strip()).is_global:
            raise ConfigurationError('Host aliases must be public IPv4 literals')
    if any('\n' in value or '\r' in value or '\0' in value for value in values.values()):
        raise ConfigurationError('Invalid deployment configuration')
    for name in ('PORT', 'CONTAINER_GATEWAY_PORT'):
        if not 1 <= int(values['DSH_PHALANX_'+name]) <= 65535:
            raise ConfigurationError(name+' must be between 1 and 65535')
    if int(values['DSH_PHALANX_PORT']) == int(values['DSH_PHALANX_CONTAINER_GATEWAY_PORT']):
        raise ConfigurationError('Entry and private gateway ports must differ')
    ipaddress.ip_address(values['DSH_PHALANX_HOST'])
    origin = urllib.parse.urlparse(values['DSH_PHALANX_PUBLIC_ORIGIN'])
    if origin.scheme not in ('http', 'https') or not origin.hostname or origin.username or origin.password or origin.path not in ('', '/') or origin.query or origin.fragment:
        raise ConfigurationError('Public origin must be an HTTP(S) origin without credentials or path')
    validate_authority(origin)
    upstream = urllib.parse.urlparse(values['DSH_PHALANX_MODEL_UPSTREAM_BASE_URL'])
    if upstream.scheme not in ('http', 'https') or not upstream.hostname or upstream.username or upstream.password or upstream.query or upstream.fragment:
        raise ConfigurationError('Model upstream must be an HTTP(S) URL without credentials, query or fragment')
    validate_authority(upstream)


def validate_storage(host, values):
    root_value, mount_value = (values.get('DSH_PHALANX_'+name) for name in ('USER_DATA_ROOT', 'USER_DATA_MOUNT'))
    if root_value is None and mount_value is None:
        return
    if not root_value or not mount_value or not Path(root_value).is_absolute() or not Path(mount_value).is_absolute():
        raise ConfigurationError('External user storage requires absolute root and mount paths')
    root, mount = host.path(root_value), host.path(mount_value).resolve(strict=True)
    platform = host.path(values['DSH_PHALANX_DATA_ROOT']).resolve()
    canonical = root.resolve()
    if mount == host.path('/') or not canonical.is_relative_to(mount):
        raise ConfigurationError('User storage must be inside the declared independent data mount')
    if canonical.is_relative_to(platform) or platform.is_relative_to(canonical):
        raise ConfigurationError('Platform and external user storage must not overlap')
    ancestor = root
    while not ancestor.exists():
        ancestor = ancestor.parent
    facts = json.loads(host.run(['findmnt', '--json', '--target', str(ancestor), '--output', 'TARGET']).stdout)
    if Path(facts['filesystems'][0]['target']).resolve() != mount:
        raise ConfigurationError('The declared user data volume is not mounted; no directory was created')
    if root.is_symlink() or root.exists() and not root.is_dir():
        raise ConfigurationError('User storage must be a directory, not a symbolic link')


def check_ports(host, args, values, successful, interactive):
    for name, address, flag in (('PORT', values['DSH_PHALANX_HOST'], '--port'), ('CONTAINER_GATEWAY_PORT', '127.0.0.1', '--gateway-port')):
        key = 'DSH_PHALANX_'+name
        while True:
            number = int(values[key])
            # A previously accepted port can be occupied only by our actual service.
            conflict = host.port_conflict(address, number, allow_managed=successful)
            if conflict is None:
                break
            if name == 'CONTAINER_GATEWAY_PORT' and not successful and args.gateway_port is None and not getattr(args, 'gateway_chosen', False):
                free = number+1
                while free <= 65535 and (free == int(values['DSH_PHALANX_PORT']) or host.port_conflict(address, free) is not None):
                    free += 1
                if free > 65535:
                    raise ConfigurationError('No free private gateway port; specify --gateway-port')
                host.tell(f'Private gateway port {number} is occupied; using {free} (saved in configuration).')
                values[key] = str(free)
                continue
            host.tell(f'{flag} {number} is unavailable: {conflict}. No occupying process was stopped.')
            if not interactive or successful:
                raise ConfigurationError(f'Choose a free {flag} and rerun the installer; {conflict}')
            values[key] = host.prompt(f'New {flag} value: ')
            origin = urllib.parse.urlparse(values['DSH_PHALANX_PUBLIC_ORIGIN'])
            if name == 'PORT' and origin.scheme == 'http' and origin.port == number:
                values['DSH_PHALANX_PUBLIC_ORIGIN'] = origin._replace(netloc=origin.netloc.rsplit(':', 1)[0]+':'+values[key]).geturl()
            if not values[key].isdigit() or not 1 <= int(values[key]) <= 65535:
                raise ConfigurationError('Port must be between 1 and 65535')


def configuration(host, args, *, entry_url, access_candidate):
    modern = args.version not in ('v0.1.0',) and not args.version.startswith('v0.1.0-')
    if not modern and (args.user_data_root is not None or args.user_data_mount is not None):
        raise ConfigurationError('External user storage options require 0.1.1 or later')
    previous = read_configuration(host)
    successful = installed_state(host) is not None
    interactive = host.terminal_available()
    values = dict(previous)
    args.gateway_chosen = 'DSH_PHALANX_CONTAINER_GATEWAY_PORT' in previous
    for option, key in OPTIONS.items():
        value = getattr(args, option)
        if value is not None:
            name = 'DSH_PHALANX_'+key
            prior = previous.get(name, '3081' if key == 'CONTAINER_GATEWAY_PORT' else None)
            if prior is not None and prior != str(value):
                if successful:
                    raise ConfigurationError('Existing successful installation configuration differs; use explicit offline configuration/storage maintenance')
            values[name] = str(value)
    missing = []
    if not interactive:
        if 'DSH_PHALANX_HOST_PUBLIC_ADDRESSES' not in values:
            missing.append('--host-public-addresses')
        if modern and 'DSH_PHALANX_PUBLIC_ORIGIN' not in values:
            missing.append('--public-origin')
        if not modern and args.model_key_file is None and 'DSH_PHALANX_MODEL_UPSTREAM_API_KEY' not in values:
            missing.append('--model-key-file')
        if missing:
            raise ConfigurationError('Missing '+', '.join(missing)+'. Example: sudo bash install.sh --public-origin http://<host>:18080 --host-public-addresses ""'+(' --model-key-file /path/to/protected-key' if not modern else ''))
    if 'DSH_PHALANX_HOST_PUBLIC_ADDRESSES' not in values:
        values['DSH_PHALANX_HOST_PUBLIC_ADDRESSES'] = host.prompt('All public IPv4 host aliases, comma-separated (empty if none): ')
    if args.model_key_file:
        path = args.model_key_file
        if path.is_symlink() or not path.is_file() or path.stat().st_mode & 0o077:
            raise ConfigurationError('Model key file must be a regular protected file (mode 0600)')
        key = path.read_text().rstrip('\r\n')
        if successful and values.get('DSH_PHALANX_MODEL_UPSTREAM_API_KEY') != key:
            raise ConfigurationError('Existing successful model configuration differs')
        if not key or any(ord(char) < 32 or ord(char) > 126 for char in key):
            raise ConfigurationError('A nonempty printable upstream credential is required')
        values['DSH_PHALANX_MODEL_UPSTREAM_API_KEY'] = key
    elif not modern and 'DSH_PHALANX_MODEL_UPSTREAM_API_KEY' not in values:
        values['DSH_PHALANX_MODEL_UPSTREAM_API_KEY'] = host.prompt('Model upstream API key: ', secret=True)
    key = values.get('DSH_PHALANX_MODEL_UPSTREAM_API_KEY')
    if key is not None and (not key or any(ord(char) < 32 or ord(char) > 126 for char in key)):
        raise ConfigurationError('A nonempty printable upstream credential is required')
    defaults = {'HOST': '0.0.0.0' if modern else '127.0.0.1', 'PORT': '18080', 'CONTAINER_GATEWAY_PORT': '3081',
                'ALLOWED_MODEL_PROVIDER': 'deepseek-official', 'ALLOWED_MODEL': 'deepseek-chat',
                'MODEL_UPSTREAM_BASE_URL': 'https://api.deepseek.com', 'SESSION_SECRET': secrets.token_hex(32),
                'DATA_ROOT': HOME_DIR+'/data', 'CONTAINER_RUNTIME': '/usr/bin/podman', 'REGISTRATION_ENABLED': 'false'}
    for name, value in defaults.items():
        values.setdefault('DSH_PHALANX_'+name, value)
    if interactive and modern and not successful:
        if args.port is None:
            values['DSH_PHALANX_PORT'] = host.prompt('Entry port ['+values['DSH_PHALANX_PORT']+']: ') or values['DSH_PHALANX_PORT']
        candidate = values.get('DSH_PHALANX_PUBLIC_ORIGIN') or access_candidate(host, values)
        if args.public_origin is None:
            values['DSH_PHALANX_PUBLIC_ORIGIN'] = host.prompt(f'Browser access URL [{candidate}]: ') or candidate
        if host.prompt('Advanced gateway/storage settings? [y/N]: ').lower() == 'y':
            gateway = host.prompt('Private gateway port ['+values['DSH_PHALANX_CONTAINER_GATEWAY_PORT']+']: ')
            args.gateway_chosen = args.gateway_chosen or bool(gateway)
            values['DSH_PHALANX_CONTAINER_GATEWAY_PORT'] = gateway or values['DSH_PHALANX_CONTAINER_GATEWAY_PORT']
            for name, label in (('USER_DATA_ROOT', 'User data directory'), ('USER_DATA_MOUNT', 'Existing data mount')):
                selected = host.prompt(label+' ['+values.get('DSH_PHALANX_'+name, '')+']: ')
                if selected:
                    values['DSH_PHALANX_'+name] = selected
    values.setdefault('DSH_PHALANX_PUBLIC_ORIGIN', entry_url(values['DSH_PHALANX_PORT'], values['DSH_PHALANX_HOST']))
    validate_configuration(host, values)
    validate_storage(host, values)
    check_ports(host, args, values, successful, interactive)
    validate_configuration(host, values)
    if not successful:
        changes = sorted(key.removeprefix('DSH_PHALANX_') for key, value in values.items() if key in previous and previous[key] != value)
        host.tell('Configuration: '+values['DSH_PHALANX_PUBLIC_ORIGIN']+'; entry port '+values['DSH_PHALANX_PORT']+'; private gateway '+values['DSH_PHALANX_CONTAINER_GATEWAY_PORT'])
        host.tell('Platform data: '+values['DSH_PHALANX_DATA_ROOT']+'; user data: '+values.get('DSH_PHALANX_USER_DATA_ROOT', values['DSH_PHALANX_DATA_ROOT']+'/users'))
        if changes:
            host.tell('Retry changes: '+', '.join(changes)+'. Existing data will be preserved.')
        if interactive and host.prompt('Continue with this configuration? [y/N]: ').lower() != 'y':
            raise ConfigurationError('Installation cancelled before downloads or deployment changes')
    return values

"""Structured installation events, operator output and private safe diagnostics."""
import contextlib
import json
import os
from pathlib import Path
import re
import secrets
import sys
import threading
import time


class Progress:
    def __init__(self, root=Path('/'), *, output='human', verbose=False, persist=True):
        self.output, self.verbose = output, verbose
        self.started = time.monotonic()
        self.phase = 'Preflight'
        self.secrets = set()
        self.observers = []
        self.lock = threading.RLock()
        self.log = None
        if persist:
            directory = root/'var/log/dsh-phalanx'
            for parent in (directory, *directory.parents):
                if parent.is_symlink(): raise OSError('Diagnostic paths must not be symbolic links')
                if parent == root: break
            directory.mkdir(parents=True, exist_ok=True, mode=0o700)
            directory.chmod(0o700)
            self.log = directory/(time.strftime('%Y%m%dT%H%M%S')+'-'+secrets.token_hex(4)+'.jsonl')
            descriptor = os.open(self.log, os.O_CREAT|os.O_EXCL|os.O_WRONLY|os.O_NOFOLLOW, 0o600)
            os.close(descriptor)

    def protect(self, *values):
        with self.lock: self.secrets.update(str(value) for value in values if value)

    def safe(self, text):
        text = re.sub(r'\x1b\[[0-9;]*[a-zA-Z]', '', str(text))
        with self.lock:
            for value in sorted(self.secrets, key=len, reverse=True): text = text.replace(value, '[REDACTED]')
        # Diagnostic carriers are untrusted: discard whole sensitive lines,
        # including quoted JSON fields and future environment/CLI key names.
        text = re.sub(r'https?://[^\s\"\']*/bootstrap[^\s\"\']*', '[REDACTED initialization link]', text, flags=re.I)
        text = re.sub(r'https?://[^\s\"\']*[?#][^\s\"\']*', '[REDACTED URL parameters]', text, flags=re.I)
        text = re.sub(r'(?im)^.*(?:authorization|(?:set[-_ ]?)?cookie|[a-z0-9_ -]*(?:key|secret|credential|password|token)[a-z0-9_ -]*)[\"\']?\s*[:=].*$', '[REDACTED sensitive line]', text)
        text = re.sub(r'(?im)^.*--[^\s]*(?:key|secret|credential|password|token)[^\s]*(?:=|\s+).*$', '[REDACTED sensitive command]', text)
        text = re.sub(r'(?i)(https?://)[^\s/@]+:[^\s/@]+@', r'\1[REDACTED]@', text)
        return text

    def subscribe(self, observer):
        self.observers.append(observer)

    def emit(self, status='running', message='', **facts):
        with self.lock:
            event = {'phase': self.phase, 'status': status, 'elapsed': round(time.monotonic()-self.started, 1), 'message': self.safe(message), **facts}
            if self.log:
                try:
                    with self.log.open('a') as file: file.write(json.dumps(event)+'\n')
                except OSError:
                    self.log = None
                    print('Diagnostic log unavailable; check disk space and permissions.', file=sys.stderr, flush=True)
            detail = event['message']
            if 'bytes' in facts:
                detail += f" {facts['bytes']} bytes" + (f" / {facts['total']} bytes" if facts.get('total') else '')
            print(f"[{event['phase']}] {status} · {event['elapsed']}s"+(f": {detail}" if detail else ''), file=sys.stderr, flush=True)
            for observer in self.observers: observer(dict(event))

    @contextlib.contextmanager
    def stage(self, name):
        self.phase = name
        self.emit(message='Starting')
        stop = threading.Event()
        def pulse():
            while not stop.wait(3): self.emit(message='Still working; waiting for this step to finish')
        thread = threading.Thread(target=pulse, daemon=True); thread.start()
        try:
            yield
        except BaseException:
            self.emit('failed', 'Step did not complete')
            raise
        else: self.emit('completed')
        finally: stop.set(); thread.join()

    def result(self, receipt, *, port=None):
        if self.output == 'json': print(json.dumps(receipt, indent=2))
        elif receipt['status'] == 'failed':
            print('Installation failed during '+receipt['phase']+': '+receipt['reason'])
            if receipt.get('diagnosticLog'): print('Diagnostic log: '+receipt['diagnosticLog'])
        else:
            print(f"dsh-phalanx {receipt['version']} installed · {time.monotonic()-self.started:.1f}s\n")
            if receipt.get('initializationUrl'):
                print('Next: open this link to create your administrator account\n'+receipt['initializationUrl']+'\n')
            print('Admin: '+receipt['adminUrl']+'\nService: ready on this host')
            print('External access: not verified; check browser access'+(f' to entry port {port}' if port else ''))
            print('If using an HTTPS reverse proxy, check its route to this entry.\nAfter signup, configure shared models in the admin page.')
            if self.verbose:
                detail = {key:value for key,value in receipt.items() if key != 'initializationUrl'}
                print(self.safe(json.dumps(detail, indent=2)), file=sys.stderr)

    def failure(self, error):
        reason = self.safe(str(error))
        self.emit('failed', reason)
        log = '/var/log/dsh-phalanx/'+self.log.name if self.log else None
        print('Inspect the managed user service: sudo journalctl _SYSTEMD_USER_UNIT=dsh-phalanx.service _UID="$(id -u dsh-phalanx)" -n 80 --no-pager', file=sys.stderr)
        print('Retry with sudo bash install.sh and corrected deployment flags; preserve the data directory.', file=sys.stderr)
        if log: print('Diagnostic log: '+log, file=sys.stderr)
        receipt = {'status':'failed', 'phase':self.phase, 'reason':reason, 'diagnosticLog':log}
        self.result(receipt)

"""The installer filesystem, terminal, socket and operating-system exit."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import platform
import subprocess
import sys
import re
import shlex
import tempfile
import tarfile
import secrets
import time
import getpass
import ipaddress
import urllib.request
import urllib.error
import urllib.parse
import fcntl
import contextlib
import shutil
import socket
import errno
import selectors


ACCOUNT = "dsh-phalanx"
def entry_url(port, listen_address):
    address = ipaddress.ip_address(listen_address)
    if address.is_unspecified:
        address = ipaddress.ip_address("127.0.0.1" if address.version == 4 else "::1")
    entry = str(address) if address.version == 4 else f"[{address}]"
    return f"http://{entry}:{port}"



class InstallError(Exception):
    pass


class Host:
    def __init__(self, root=Path("/"), command=None, *, system=None, machine=None, uid=None):
        self.root = root.resolve()
        self.command = command or subprocess.run
        self.injected_command = command is not None
        self.progress = None
        self.system = system or platform.system()
        self.machine = machine or platform.machine()
        self.uid = os.geteuid() if uid is None else uid
        self.clock = time.monotonic
        self.pause = time.sleep

    def path(self, path):
        return self.root / str(path).lstrip("/")

    def run(self, arguments, *, check=True, input_file=None, env=None, cwd=None):
        sensitive = 'bootstrap-link' in arguments
        streaming = not sensitive and (arguments[0] == 'apt-get' or 'pull' in arguments or 'load' in arguments or (self.progress and self.progress.verbose))
        if self.progress and self.progress.verbose:
            self.progress.emit(message='Command: '+shlex.join(arguments))
        with contextlib.ExitStack() as stack:
            source = stack.enter_context(input_file.open('rb')) if input_file else None
            if self.injected_command:
                result = self.command(arguments, capture_output=True, text=True, stdin=source, env=env, cwd=cwd)
                if self.progress and streaming:
                    for line in (result.stdout+result.stderr).splitlines(): self.progress.emit(message=line)
            else:
                process = subprocess.Popen(arguments, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=source or subprocess.DEVNULL, env=env, cwd=cwd)
                captured = {'out':[], 'err':[]}; pending = {'out':b'', 'err':b''}
                try:
                    with selectors.DefaultSelector() as selector:
                        for stream,key in ((process.stdout,'out'),(process.stderr,'err')): selector.register(stream, selectors.EVENT_READ, key)
                        while selector.get_map():
                            for selected,_ in selector.select(1):
                                key=selected.data; chunk=os.read(selected.fileobj.fileno(), 65536)
                                if not chunk:
                                    selector.unregister(selected.fileobj)
                                    if pending[key] and streaming and self.progress: self.progress.emit(message=pending[key].decode(errors='replace'))
                                    continue
                                captured[key].append(chunk); pending[key]+=chunk
                                while b'\n' in pending[key] or b'\r' in pending[key]:
                                    match=re.search(b'[\r\n]',pending[key]); line=pending[key][:match.start()]; pending[key]=pending[key][match.end():]
                                    if streaming and self.progress: self.progress.emit(message=line.decode(errors='replace'))
                    result=subprocess.CompletedProcess(arguments, process.wait(), b''.join(captured['out']).decode(errors='replace'), b''.join(captured['err']).decode(errors='replace'))
                finally:
                    if process.poll() is None: process.terminate(); process.wait()
                    process.stdout.close(); process.stderr.close()
        if check and result.returncode != 0:
            raise InstallError(f"{arguments[0]} failed (exit {result.returncode}): {result.stderr[:1500]}")
        return result

    def request(self, url, *, authority=None):
        headers = {'User-Agent':'dsh-phalanx-installer/0.1.2', **({'Host':authority} if authority else {})}
        request=urllib.request.Request(url,headers=headers)
        opener=urllib.request.build_opener(urllib.request.ProxyHandler({})) if authority else urllib.request.build_opener()
        with opener.open(request,timeout=60) as response:
            chunks=[]; received=0; total=int(response.headers.get('Content-Length','0') or '0')
            while True:
                block=response.read(65536)
                if not block: break
                chunks.append(block); received+=len(block)
                if self.progress and authority is None: self.progress.emit(message='Downloaded', bytes=received, total=total or None)
            return b''.join(chunks)

    def mkdir(self, path, mode=0o755):
        destination = self.path(path)
        for parent in (destination, *destination.parents):
            if parent.is_symlink():
                raise InstallError("Installation paths must not contain symbolic links")
            if parent == self.root:
                break
        destination.mkdir(parents=True, mode=0o755 if mode is None else mode, exist_ok=True)
        if mode is not None:
            destination.chmod(mode)
        return destination

    def atomic(self, path, text, mode=0o600):
        destination = self.path(path)
        if destination.is_symlink():
            raise InstallError("Managed configuration must not be a symbolic link")
        self.mkdir(str(Path(path).parent), mode=None)
        descriptor, temporary = tempfile.mkstemp(prefix=".install-", dir=destination.parent)
        try:
            with os.fdopen(descriptor, "w") as file:
                os.fchmod(file.fileno(), mode)
                file.write(text)
                file.flush()
                os.fsync(file.fileno())
            os.replace(temporary, destination)
        finally:
            Path(temporary).unlink(missing_ok=True)

    def user(self, uid, arguments, **kwargs):
        environment = {"PATH": "/usr/sbin:/usr/bin:/sbin:/bin", "LANG": "C.UTF-8", "HOME": HOME_DIR, "XDG_RUNTIME_DIR": f"/run/user/{uid}",
                       "DBUS_SESSION_BUS_ADDRESS": f"unix:path=/run/user/{uid}/bus"}
        return self.run(["runuser", "-u", ACCOUNT, "--", *arguments], env=environment, cwd=self.path(HOME_DIR), **kwargs)

    def tell(self, text):
        self.progress.emit(message=text) if self.progress else print(text, file=sys.stderr)

    def terminal_available(self):
        try:
            with open('/dev/tty', 'r') as terminal:
                return terminal.isatty()
        except OSError:
            return False

    def port_conflict(self, address, port, *, allow_managed=False):
        parsed = ipaddress.ip_address(address)
        if allow_managed:
            account = self.run(['getent', 'passwd', ACCOUNT], check=False)
            if account.returncode == 0:
                uid = int(account.stdout.split(':')[2])
                probe = ipaddress.ip_address('127.0.0.1' if parsed.version == 4 else '::1') if parsed.is_unspecified else parsed
                if self.listener_pid(uid, port, probe):
                    return None
        with socket.socket(socket.AF_INET if parsed.version == 4 else socket.AF_INET6) as listener:
            # Match the managed TCP server: closed connections in TIME_WAIT
            # do not reserve a port; an active unrelated listener still does.
            listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            try:
                listener.bind((address, port))
            except OSError as error:
                if error.errno == errno.EADDRINUSE:
                    info = self.run(['ss', '-ltnp', f'sport = :{port}'], check=False)
                    return 'port occupied; '+info.stdout.strip()[:1000]
                return 'cannot bind requested address/port (errno '+str(error.errno)+')'
        return None

    def prompt(self, label, secret=False):
        try:
            with open("/dev/tty", "r") as terminal, open("/dev/tty", "w") as display:
                if secret:
                    return getpass.getpass(label, stream=display)
                display.write(label)
                display.flush()
                return terminal.readline().strip()
        except OSError:
            raise InstallError("No terminal available; provide --public-origin and --host-public-addresses")

    def listener_pid(self, uid, port, address):
        result = self.user(uid, ["systemctl", "--user", "show", "--property=MainPID", "--value", "dsh-phalanx.service"], check=False)
        if result.returncode != 0:
            return 0
        pid = int(result.stdout.strip() or "0")
        try:
            sockets = {os.readlink(file) for file in self.path(f"/proc/{pid}/fd").iterdir()}
            packed = address.packed
            encoded = (packed[::-1] if address.version == 4 else b"".join(packed[index:index+4][::-1] for index in range(0, 16, 4))).hex().upper()
            table = self.path("/proc/net/tcp"+("6" if address.version == 6 else ""))
            for line in table.read_text().splitlines()[1:]:
                fields = line.split()
                local, number = fields[1].split(":")
                if fields[3] == "0A" and int(number, 16) == port and local in (encoded, "0"*len(encoded)) and f"socket:[{fields[9]}]" in sockets:
                    return pid
        except OSError:
            pass
        return 0

    def ready(self, uid, port, listen_address, public_origin):
        entry = entry_url(port, listen_address)
        address = ipaddress.ip_address(urllib.parse.urlparse(entry).hostname)
        public = urllib.parse.urlparse(public_origin)
        hostname = ipaddress.ip_address(public.hostname).compressed if ":" in public.hostname else public.hostname.encode("idna").decode("ascii")
        authority = f"[{hostname}]" if ":" in hostname else hostname
        if public.port is not None and public.port != {"http": 80, "https": 443}[public.scheme]:
            authority += f":{public.port}"
        deadline = self.clock()+90
        http_failed = False
        while True:
            pid = 0
            try:
                pid = self.listener_pid(uid, port, address)
                if pid:
                    self.request(entry+"/login", authority=authority)
                    if self.listener_pid(uid, port, address) == pid:
                        return
            except OSError:
                http_failed = bool(pid)
            if self.clock() >= deadline:
                details=self.user(uid, ['systemctl','--user','show','dsh-phalanx.service','--property=ActiveState,SubState,ExecMainStatus,MainPID'], check=False)
                journal=self.run(['journalctl','_SYSTEMD_USER_UNIT=dsh-phalanx.service',f'_UID={uid}','-n','40','--no-pager'], check=False)
                if self.progress:
                    self.progress.emit(message='Service facts: '+details.stdout)
                    for line in journal.stdout.splitlines(): self.progress.emit(message=line)
                conflict = self.port_conflict(listen_address, port, allow_managed=True)
                if conflict:
                    raise InstallError(f'Entry port {port} cannot be bound by the managed service: {conflict}. No occupying process was stopped.')
                status = self.user(uid, ['systemctl','--user','show','--property=ExecMainStatus','--value','dsh-phalanx.service'],check=False)
                exit_status = int(status.stdout.strip() or '0') if status.returncode == 0 else 0
                if exit_status:
                    raise InstallError(f'Managed service process exited with status {exit_status}; inspect the service journal above.')
                if http_failed:
                    raise InstallError('Managed listener was found but HTTP readiness failed; inspect the service journal above.')
                raise InstallError('Managed service did not own a ready listener; root cause is unknown. Inspect service facts and journal above.')
            if self.progress: self.progress.emit(message="Waiting for the managed process to own a ready HTTP listener")
            self.pause(1)



"""Ubuntu installation command. Host owns filesystem and operating-system I/O."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import platform
import subprocess
import sys
import re
import shlex
import tempfile
import tarfile
import secrets
import time
import getpass
import ipaddress
import urllib.request
import urllib.error
import urllib.parse
import fcntl
import contextlib
import shutil
import socket
import errno

ACCOUNT = "dsh-phalanx"
HOME_DIR = "/var/lib/dsh-phalanx"
CONFIG = "/etc/dsh-phalanx/environment"
STATE = "/etc/dsh-phalanx/install-state.json"
CURRENT = "/opt/dsh-phalanx/current"
UNIT = HOME_DIR+"/.config/systemd/user/dsh-phalanx.service"
PACKAGES = ("podman", "uidmap", "passt", "fuse-overlayfs", "dbus-user-session", "apparmor", "apparmor-utils")

IMAGE = "ghcr.io/dake6767/dsh-phalanx"
ASSETS = ("dsh-phalanx-linux-amd64.tar.gz", "dsh-phalanx-dsh-linux-amd64.oci.tar")
CANDIDATE = re.compile(r"v0\.1\.[01]-rc\.[1-9][0-9]*\Z")



def access_candidate(host, values):
    address = ipaddress.ip_address(values['DSH_PHALANX_HOST'])
    if not address.is_unspecified:
        return entry_url(values['DSH_PHALANX_PORT'], str(address))
    aliases = values['DSH_PHALANX_HOST_PUBLIC_ADDRESSES'].split(',')
    candidates = [value.strip() for value in aliases if value.strip()]
    if not candidates:
        candidates = host.run(['hostname', '-I']).stdout.split()
    for candidate in candidates:
        parsed = ipaddress.ip_address(candidate)
        if not parsed.is_loopback and not parsed.is_link_local and not parsed.is_unspecified:
            return entry_url(values['DSH_PHALANX_PORT'], str(parsed))
    return entry_url(values['DSH_PHALANX_PORT'], str(address))



def options(arguments):
    class Parser(argparse.ArgumentParser):
        def error(self, message): raise InstallError(message)
    parser = Parser(description="Install dsh-phalanx on Ubuntu 24.04 amd64")
    parser.add_argument("--version", default="latest")
    parser.add_argument("--output", choices=("human", "json"), default="human")
    parser.add_argument("--verbose", action="store_true", help="Show sanitized commands and identity details")
    parser.add_argument("--bundle-dir", type=Path, help="Explicit private candidate archive handoff")
    parser.add_argument("--model-key-file", type=Path, help="Read deployer credential from a protected file")
    parser.add_argument("--host-public-addresses", help="Complete public IPv4 aliases; pass an empty string only if none")
    parser.add_argument("--model-base-url")
    parser.add_argument("--model-provider")
    parser.add_argument("--model")
    parser.add_argument("--listen-address")
    parser.add_argument("--port", type=int)
    parser.add_argument("--gateway-port", type=int, help="Private loopback model/network gateway port")
    parser.add_argument("--public-origin")
    parser.add_argument('--user-data-root', help='User home/workspace directory on an existing mounted data volume')
    parser.add_argument('--user-data-mount', help='Exact expected mount point containing the user data directory')
    return parser.parse_args(arguments)


def digest(path):
    result = hashlib.sha256()
    with path.open("rb") as file:
        for block in iter(lambda: file.read(1024*1024), b""):
            result.update(block)
    return result.hexdigest()


def verify_manifest(directory, version, archive=True, *, assets=True):
    manifest = json.loads((directory / "manifest.json").read_text())
    image = manifest.get("image", {})
    files = manifest.get("files", {})
    if (manifest.get("schema") != 1 or not CANDIDATE.fullmatch(manifest.get("tag", "")) or
            manifest.get("targetVersion") != manifest["tag"].split("-rc.")[0][1:] or manifest.get("platform") != "linux/amd64" or
            not re.fullmatch(r"[a-f0-9]{40}", manifest.get("commit", "")) or
            not re.fullmatch(r"[a-f0-9]{40}", manifest.get("dshRevision", "")) or
            not re.fullmatch(r"[1-9][0-9]*", manifest.get("runId", "")) or
            image.get("name") != IMAGE or image.get("tag") != manifest["tag"][1:] or
            not re.fullmatch(r"sha256:[a-f0-9]{64}", image.get("digest", "")) or
            image.get("reference") != IMAGE+"@"+image["digest"] or
            set(files) != set(ASSETS) or
            any(not re.fullmatch(r"[a-f0-9]{64}", value) for value in files.values()) or
            not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+", manifest.get("toolchain", {}).get("node", ""))):
        raise InstallError("Invalid release manifest")
    if version != manifest["tag"] and version != "v"+manifest["targetVersion"]:
        raise InstallError("Requested version does not match the manifest")
    expected = "".join(f"{files[name]}  {name}\n" for name in ASSETS)
    if (directory / "SHA256SUMS").read_text() != expected:
        raise InstallError("Checksum inventory mismatch")
    for name in (ASSETS if archive else ASSETS[:1]) if assets else ():
        file = directory / name
        if file.is_symlink() or not file.is_file() or digest(file) != files[name]:
            raise InstallError(f"Checksum mismatch: {name}")
    return manifest


def acquire(host, args, destination):
    if args.bundle_dir is not None:
        if not CANDIDATE.fullmatch(args.version):
            raise InstallError("Private archive handoff requires an explicit candidate version")
        return args.bundle_dir, verify_manifest(args.bundle_dir, args.version)
    api = "https://api.github.com/repos/dake6767/dsh-phalanx"
    if args.version != "latest" and args.version not in ("v0.1.0", "v0.1.1") and not CANDIDATE.fullmatch(args.version):
        raise InstallError("Specify latest, v0.1.0, v0.1.1, or an explicit candidate tag")
    release = json.loads(host.request(api+"/releases/"+("latest" if args.version == "latest" else "tags/"+args.version)))
    version = release.get("tag_name")
    if release.get("draft") or (version in ("v0.1.0", "v0.1.1") and release.get("prerelease")) or (args.version == "latest" and version not in ("v0.1.0", "v0.1.1")):
        raise InstallError("Latest installation requires a completed stable release")
    if args.version != "latest" and version != args.version:
        raise InstallError("Release identity mismatch")
    required = {"manifest.json", "SHA256SUMS", *ASSETS}
    if version in ("v0.1.0", "v0.1.1"):
        required.update(("acceptance.json", "acceptance.md", "release.json"))
    if len(release["assets"]) != len(required) or {item["name"] for item in release["assets"]} != required:
        raise InstallError("Release asset inventory is incomplete or unexpected")
    base = f"https://github.com/dake6767/dsh-phalanx/releases/download/{version}/"
    state = installed_state(host)
    cached = host.path('/etc/dsh-phalanx/installed-manifest.json')
    if state and state['version'] == version and cached.is_file() and not cached.is_symlink():
        manifest = json.loads(cached.read_text())
        if manifest['commit'] != state['commit'] or manifest['image']['digest'] != state['imageDigest'] or manifest['files'][ASSETS[0]] != state['platformSha256']:
            raise InstallError('Installed manifest and receipt disagree')
    else:
        for name in ('manifest.json', 'SHA256SUMS'):
            (destination / name).write_bytes(host.request(base+name))
        metadata = verify_manifest(destination, version, archive=False, assets=False)
        same = state and state['candidate'] == metadata['tag'] and state['commit'] == metadata['commit'] and state['imageDigest'] == metadata['image']['digest'] and state['platformSha256'] == metadata['files'][ASSETS[0]]
        if same:
            manifest = metadata
        else:
            sha = metadata['files'][ASSETS[0]]
            cached_asset = host.path('/var/cache/dsh-phalanx/'+sha+'.tar.gz')
            if cached_asset.is_file() and not cached_asset.is_symlink() and digest(cached_asset) == sha:
                shutil.copyfile(cached_asset, destination / ASSETS[0])
                host.tell('Reusing checksum-verified platform download.')
            else:
                (destination / ASSETS[0]).write_bytes(host.request(base+ASSETS[0]))
            manifest = verify_manifest(destination, version, archive=False)
    reference = json.loads(host.request(api+"/git/ref/tags/"+version))["object"]
    for _ in range(4):
        if reference["type"] == "commit":
            break
        if reference["type"] != "tag":
            raise InstallError("Release tag must identify a commit")
        reference = json.loads(host.request(api+"/git/tags/"+reference["sha"]))["object"]
    if reference["type"] != "commit" or reference["sha"] != manifest["commit"]:
        raise InstallError("Release tag and manifest source commit differ")
    if (destination / ASSETS[0]).is_file():
        cache = host.mkdir('/var/cache/dsh-phalanx', 0o700) / (manifest['files'][ASSETS[0]]+'.tar.gz')
        temporary = cache.with_suffix('.next')
        shutil.copyfile(destination / ASSETS[0], temporary)
        temporary.chmod(0o600)
        os.replace(temporary, cache)
    return destination, manifest


def dependencies(host):
    installed = host.run(["dpkg-query", "-W", "-f=${db:Status-Abbrev}\\n", *PACKAGES], check=False)
    if installed.returncode != 0 or installed.stdout.splitlines() != ["ii "]*len(PACKAGES):
        env = {**os.environ, "DEBIAN_FRONTEND": "noninteractive"}
        host.run(["apt-get", "-o", "DPkg::Lock::Timeout=600", "update"], env=env)
        host.run(["apt-get", "-o", "DPkg::Lock::Timeout=600", "install", "-y", "--no-install-recommends", *PACKAGES], env=env)
    sysctl = []
    for key, value in (("kernel.unprivileged_userns_clone", "1"), ("user.max_user_namespaces", "65536")):
        path = host.path("/proc/sys/"+key.replace(".", "/"))
        if path.exists() and path.read_text().strip() == "0":
            sysctl.append(key+"="+value)
    if sysctl:
        host.atomic("/etc/sysctl.d/90-dsh-phalanx.conf", "\n".join(sysctl)+"\n", 0o644)
        host.run(["sysctl", "--load", str(host.path("/etc/sysctl.d/90-dsh-phalanx.conf"))])
    restricted = host.path("/proc/sys/kernel/apparmor_restrict_unprivileged_userns")
    if restricted.exists() and restricted.read_text().strip() == "1":
        for binary in ("podman", "pasta"):
            profile = "/etc/apparmor.d/"+binary
            if not host.path(profile).exists():
                profile = "/etc/apparmor.d/dsh-phalanx-"+binary
                host.atomic(profile, "abi <abi/4.0>,\ninclude <tunables/global>\n"+
                            f"profile dsh-phalanx-{binary} /usr/bin/{binary} flags=(unconfined) {{\n  userns,\n}}\n", 0o644)
            host.run(["apparmor_parser", "-r", str(host.path(profile))])


def identity(host):
    existing = host.run(["getent", "passwd", ACCOUNT], check=False)
    if existing.returncode == 2:
        host.run(["useradd", "--create-home", "--user-group", "--home-dir", HOME_DIR, "--shell", "/usr/sbin/nologin", ACCOUNT])
        existing = host.run(["getent", "passwd", ACCOUNT])
    elif existing.returncode != 0:
        raise InstallError("Cannot inspect the service identity")
    row = existing.stdout.strip().split(":")
    if len(row) != 7 or row[5] != HOME_DIR or row[6] != "/usr/sbin/nologin" or int(row[2]) == 0 or int(row[3]) == 0:
        raise InstallError("Reserved service account has incompatible identity or home")
    uid, gid = int(row[2]), int(row[3])
    for table, flag in (("subuid", "--add-subuids"), ("subgid", "--add-subgids")):
        rows = [line.split(":") for line in host.path("/etc/"+table).read_text().splitlines() if line]
        own = [item for item in rows if item[0] in (ACCOUNT, str(uid))]
        if own and not any(int(item[2]) >= 65536 for item in own):
            raise InstallError("Service identity needs a contiguous 65536-entry subordinate-ID range")
        for selected in own:
            start, end = int(selected[1]), int(selected[1])+int(selected[2])
            if start < 65536 or end > 2**32 or any(other is not selected and start < int(other[1])+int(other[2]) and int(other[1]) < end for other in rows):
                raise InstallError("Service subordinate-ID ranges must be unprivileged and nonoverlapping")
        if not own:
            start = max([100000, *(int(item[1])+int(item[2]) for item in rows)])
            if start+65535 >= 2**32:
                raise InstallError("No subordinate-ID range is available")
            host.run(["usermod", flag, f"{start}-{start+65535}", ACCOUNT])
    host.mkdir(HOME_DIR, 0o700)
    host.run(["chown", f"{uid}:{gid}", str(host.path(HOME_DIR))])
    storage = HOME_DIR+"/.config/containers/storage.conf"
    if not host.path(storage).exists():
        host.atomic(storage, '[storage]\ndriver = "overlay"\n[storage.options.overlay]\nmount_program = "/usr/bin/fuse-overlayfs"\n', 0o600)
    host.run(["chown", "-R", f"{uid}:{gid}", str(host.path(HOME_DIR+"/.config"))])
    host.run(["loginctl", "enable-linger", ACCOUNT])
    host.run(["systemctl", "start", f"user@{uid}.service"])
    info = json.loads(host.user(uid, ["podman", "info", "--format", "json"]).stdout)
    if info["host"]["security"]["rootless"] is not True or info["host"]["cgroupVersion"] != "v2":
        raise InstallError("Rootless Podman and cgroup v2 are required")
    return uid, gid


def supply_image(host, uid, directory, manifest, archive):
    reference = manifest["image"]["reference"]
    present = host.user(uid, ["podman", "image", "exists", reference], check=False)
    if present.returncode == 1:
        if archive:
            host.user(uid, ["podman", "load"], input_file=directory / ASSETS[1])
            ids = host.user(uid, ["podman", "images", "--filter", "label=org.opencontainers.image.revision="+manifest["commit"], "--format", "{{.ID}}"]).stdout.splitlines()
            matches = []
            for image_id in set(ids):
                facts = json.loads(host.user(uid, ["podman", "image", "inspect", image_id]).stdout)[0]
                if facts["Digest"] == manifest["image"]["digest"]:
                    matches.append(image_id)
            if len(matches) != 1:
                raise InstallError("Archive did not supply exactly one matching candidate image")
            host.user(uid, ["podman", "tag", matches[0], IMAGE+":"+manifest["image"]["tag"]])
        else:
            host.user(uid, ["podman", "pull", reference])
    elif present.returncode != 0:
        raise InstallError("Cannot inspect rootless image storage")
    image = json.loads(host.user(uid, ["podman", "image", "inspect", reference]).stdout)[0]
    config = image["Config"]
    if (image["Digest"] != manifest["image"]["digest"] or image["Architecture"] != "amd64" or image["Os"] != "linux" or
            config["User"] != "node" or config["Labels"].get("dsh.revision") != manifest["dshRevision"] or
            config["Labels"].get("org.opencontainers.image.revision") != manifest["commit"]):
        raise InstallError("Imported/pulled image identity does not match this platform release")
    command = config.get("Cmd")
    if not isinstance(command, list) or len(command) < 2 or not all(isinstance(part, str) and part for part in command):
        raise InstallError("Image does not declare its official runtime command")
    return command


def stage_platform(host, directory, manifest):
    sha = manifest["files"][ASSETS[0]]
    target = f'/opt/dsh-phalanx/releases/{manifest["tag"]}-{sha[:16]}'
    host.mkdir("/opt/dsh-phalanx")
    releases = host.mkdir("/opt/dsh-phalanx/releases")
    if not host.path(target).exists():
        with tempfile.TemporaryDirectory(prefix=".install-", dir=releases) as temporary:
            with tarfile.open(directory / ASSETS[0], "r:gz") as archive:
                archive.extractall(temporary, filter="data")
            staging = Path(temporary)
            for name in ("start", "node/bin/node", "dist/composition/cli.js", "admin-ui/dist/community.html"):
                if not (staging / name).is_file():
                    raise InstallError("Platform archive lacks required runtime assets")
            build = json.loads((staging / "build-info.json").read_text())
            if build.get("commit") != manifest["commit"] or build.get("platform") != "linux/amd64":
                raise InstallError("Packaged product identity mismatch")
            node = host.run([str(staging / "node/bin/node"), "--version"]).stdout.strip()
            if node != "v"+manifest["toolchain"]["node"]:
                raise InstallError("Bundled Node identity mismatch")
            (staging / ".artifact-sha256").write_text(sha)
            staging.chmod(0o755)
            os.rename(staging, host.path(target))
    if host.path(target+"/.artifact-sha256").read_text() != sha:
        raise InstallError("Existing release directory has a conflicting identity")
    root = host.path(target)
    for path in (root, *root.rglob("*")):
        if not path.is_symlink():
            path.chmod(0o755 if path.is_dir() or path.stat().st_mode & 0o111 else 0o644)
    return target


def environment_text(values):
    return "".join(f'{key}="'+value.replace("\\", "\\\\").replace('"', '\\"')+'"\n' for key, value in sorted(values.items()))



def prepare_user_storage(host, uid, gid, values):
    root_value, mount_value = (values.get('DSH_PHALANX_'+name) for name in ('USER_DATA_ROOT', 'USER_DATA_MOUNT'))
    if root_value is None and mount_value is None:
        return
    if not root_value or not mount_value or not Path(root_value).is_absolute() or not Path(mount_value).is_absolute():
        raise InstallError('External user storage requires absolute root and mount paths')
    validate_storage(host, values)
    root = host.path(root_value)
    if not root.exists() or not any(root.iterdir()):
        host.mkdir(root_value, 0o700)
        host.run(['chown', f'{uid}:{gid}', str(root)])
    # Existing nonempty directories and their ownership are left for runtime
    # identity validation; adoption and migration are never implicit here.


def activate(host, uid, gid, target, values, manifest, version):
    unit = ('[Unit]\nDescription=dsh-phalanx community platform\nAfter=network-online.target\n\n[Service]\nType=simple\n'+
            f'EnvironmentFile={CONFIG}\nWorkingDirectory={HOME_DIR}\nExecStart={CURRENT}/start\n'+
            'Restart=on-failure\nRestartSec=2\nTimeoutStopSec=45\nKillMode=control-group\nDelegate=yes\nUMask=0077\n\n[Install]\nWantedBy=default.target\n')
    old_config = host.path(CONFIG).read_text() if host.path(CONFIG).exists() else None
    old_unit = host.path(UNIT).read_text() if host.path(UNIT).exists() else None
    current = host.path(CURRENT)
    if current.exists() and not current.is_symlink():
        raise InstallError("Current release path must be an installer-managed symlink")
    previous = os.readlink(current) if current.is_symlink() else None
    persisted = dict(values)
    if old_config is not None and 'DSH_PHALANX_CONTAINER_GATEWAY_PORT=' not in old_config and installed_state(host) and values['DSH_PHALANX_CONTAINER_GATEWAY_PORT'] == '3081':
        persisted.pop('DSH_PHALANX_CONTAINER_GATEWAY_PORT')
    text = environment_text(persisted)
    active = host.user(uid, ["systemctl", "--user", "is-active", "--quiet", "dsh-phalanx.service"], check=False).returncode == 0
    unchanged = previous == str(host.path(target)) and old_config == text and old_unit == unit
    if not unchanged or not active:
        host.mkdir("/etc/dsh-phalanx", 0o750)
        host.atomic(CONFIG, text, 0o640)
        host.run(["chown", f"0:{gid}", str(host.path("/etc/dsh-phalanx")), str(host.path(CONFIG))])
        host.atomic(UNIT, unit, 0o644)
        host.run(["chown", "-R", f"{uid}:{gid}", str(host.path(HOME_DIR+"/.config/systemd"))])
        replacement = host.path(CURRENT+".next")
        replacement.unlink(missing_ok=True)
        replacement.symlink_to(host.path(target))
        try:
            host.user(uid, ["systemctl", "--user", "daemon-reload"])
            host.user(uid, ["systemctl", "--user", "stop", "dsh-phalanx.service"])
            os.replace(replacement, current)
            host.user(uid, ["systemctl", "--user", "enable", "--now", "dsh-phalanx.service"])
            host.ready(uid, int(values["DSH_PHALANX_PORT"]), values["DSH_PHALANX_HOST"], values["DSH_PHALANX_PUBLIC_ORIGIN"])
        except (InstallError, OSError):
            replacement.unlink(missing_ok=True)
            host.user(uid, ["systemctl", "--user", "stop", "dsh-phalanx.service"])
            if previous is not None:
                current.unlink(missing_ok=True)
                current.symlink_to(previous)
                if old_config is not None:
                    host.atomic(CONFIG, old_config, 0o640)
                    host.run(["chown", f"0:{gid}", str(host.path(CONFIG))])
                if old_unit is not None:
                    host.atomic(UNIT, old_unit, 0o644)
                host.user(uid, ["systemctl", "--user", "daemon-reload"])
                host.user(uid, ["systemctl", "--user", "start", "dsh-phalanx.service"])
            else:
                host.user(uid, ["systemctl", "--user", "disable", "dsh-phalanx.service"], check=False)
                current.unlink(missing_ok=True)
            raise
    else:
        host.ready(uid, int(values["DSH_PHALANX_PORT"]), values["DSH_PHALANX_HOST"], values["DSH_PHALANX_PUBLIC_ORIGIN"])
    receipt = {"status": "installed", "version": version, "candidate": manifest["tag"], "commit": manifest["commit"],
               "platformSha256": manifest["files"][ASSETS[0]], "imageDigest": manifest["image"]["digest"], "serviceUser": ACCOUNT,
               "configuration": CONFIG, "entry": values["DSH_PHALANX_PUBLIC_ORIGIN"],
               "adminUrl": values["DSH_PHALANX_PUBLIC_ORIGIN"].rstrip('/')+'/admin',
               "bootstrapCredentialFile": HOME_DIR+"/data/bootstrap-credential", "changed": not unchanged}
    link = ''
    if manifest['targetVersion'] == '0.1.1':
        link = host.user(uid, [str(host.path(CURRENT+'/start')), 'bootstrap-link',
                          '--data-root', str(host.path(values['DSH_PHALANX_DATA_ROOT'])),
                          '--origin', values['DSH_PHALANX_PUBLIC_ORIGIN']]).stdout.strip()
    host.atomic(STATE, json.dumps(receipt, indent=2)+"\n")
    host.atomic("/etc/dsh-phalanx/installed-manifest.json", json.dumps(manifest)+"\n")
    host.path('/etc/dsh-phalanx/install-draft').unlink(missing_ok=True)
    # The invitation is operator output only; never persist it in the receipt.
    output = {**receipt, **({'initializationUrl': link} if urllib.parse.urlparse(link).path == '/bootstrap' else {})}
    return output


def main(arguments=None, host=None):
    host = host or Host()
    arguments = sys.argv[1:] if arguments is None else arguments
    output = 'json' if '--output=json' in arguments or any(arguments[i:i+2] == ['--output','json'] for i in range(len(arguments))) else 'human'
    try:
        report = Progress(host.root, output=output, verbose='--verbose' in arguments, persist=host.uid == 0 and host.system == 'Linux' and host.machine == 'x86_64')
    except OSError as error:
        report = Progress(host.root, output=output, persist=False)
        report.failure(error)
        return 1
    host.progress = report
    try:
        with report.stage('Preflight'):
            args = options(arguments)
            if host.system != 'Linux' or host.machine != 'x86_64':
                raise InstallError('Installation supports only Ubuntu 24.04 LTS amd64')
            if host.uid != 0: raise InstallError('Run the installer with sudo')
            release = dict(line.split('=',1) for line in host.path('/etc/os-release').read_text().splitlines() if '=' in line)
            if shlex.split(release.get('ID','')) != ['ubuntu'] or shlex.split(release.get('VERSION_ID','')) != ['24.04']:
                raise InstallError('Installation supports only Ubuntu 24.04 LTS amd64')
        lock = host.mkdir('/run/lock', mode=None)/'dsh-phalanx-install.lock'
        descriptor = os.open(lock, os.O_CREAT|os.O_RDWR|os.O_NOFOLLOW, 0o600)
        with os.fdopen(descriptor,'w') as file, tempfile.TemporaryDirectory(prefix='dsh-phalanx-download-') as temporary:
            with report.stage('Installation lock'):
                while True:
                    try: fcntl.flock(file, fcntl.LOCK_EX|fcntl.LOCK_NB); break
                    except BlockingIOError:
                        report.emit(message='Waiting for another installer to release the installation lock')
                        host.pause(1)
            with report.stage('Configuration'):
                values=configuration(host,args,entry_url=entry_url,access_candidate=access_candidate)
                report.protect(*(value for key,value in values.items() if key.endswith(('_KEY','_SECRET'))))
            with report.stage('Download and verification'):
                directory,manifest=acquire(host,args,Path(temporary))
            values['DSH_PHALANX_CONTAINER_IMAGE']=manifest['image']['reference']
            state=installed_state(host)
            if state and state['candidate']==manifest['tag'] and state['commit']==manifest['commit'] and state['imageDigest']==manifest['image']['digest']:
                with report.stage('Existing installation'):
                    account=host.run(['getent','passwd',ACCOUNT]).stdout.split(':'); uid,gid=int(account[2]),int(account[3])
                    active=host.user(uid,['systemctl','--user','is-active','--quiet','dsh-phalanx.service'],check=False).returncode==0
                    if not active: raise InstallError('Existing service is not active; inspect or restart its user-systemd unit before retrying')
                    previous='/'+str(host.path(CURRENT).resolve().relative_to(host.root))
                    if host.path(CURRENT+'/.artifact-sha256').read_text()!=state['platformSha256']:
                        raise InstallError('Installed platform identity differs from the successful receipt')
                    command=supply_image(host,uid,directory,manifest,args.bundle_dir is not None)
                    values['DSH_PHALANX_RUNTIME_COMMAND']=command[0]
                    values['DSH_PHALANX_RUNTIME_ARGS_JSON']=json.dumps(command[1:],separators=(',',':'))
                    host.tell('Installed '+state['version']+'; service active; configuration unchanged. Verifying readiness.')
                    receipt=activate(host,uid,gid,previous,values,manifest,state['version'])
            else:
                if state is None: host.atomic('/etc/dsh-phalanx/install-draft',environment_text(values))
                with report.stage('Dependencies'): dependencies(host)
                with report.stage('Identity and directories'):
                    uid,gid=identity(host); prepare_user_storage(host,uid,gid,values)
                with report.stage('Platform verification and staging'): target=stage_platform(host,directory,manifest)
                with report.stage('Runtime image'):
                    command=supply_image(host,uid,directory,manifest,args.bundle_dir is not None)
                    values['DSH_PHALANX_RUNTIME_COMMAND']=command[0]
                    values['DSH_PHALANX_RUNTIME_ARGS_JSON']=json.dumps(command[1:],separators=(',',':'))
                with report.stage('Service activation'):
                    receipt=activate(host,uid,gid,target,values,manifest,args.version if args.version!='latest' else 'v'+manifest['targetVersion'])
            report.result(receipt,port=values['DSH_PHALANX_PORT'])
        return 0
    except (InstallError,OSError,ValueError,KeyError,TypeError,tarfile.TarError) as error:
        report.failure(error)
        return 1


if __name__ == '__main__': sys.exit(main())

DSH_PHALANX_INSTALLER_PYTHON
