/** Shared presentation values for the independent platform pages and management UI. */
export const PLATFORM_THEME_CSS = `
:root,.light,[data-theme="light"]{color-scheme:light;--accent:#1d3430;--accent-foreground:#fff;--background:#f6f7f4;--foreground:#1d302d;--surface:#fff;--surface-foreground:var(--foreground);--surface-secondary:#f9faf8;--overlay:var(--surface);--overlay-foreground:var(--foreground);--muted:#66776b;--border:#e5eae4;--separator:var(--border);--default:#edf1e8;--default-foreground:var(--foreground);--field-background:#fafbf8;--field-foreground:var(--foreground);--field-border:var(--border);--field-placeholder:#7c897f;--focus:var(--accent);--radius:.5rem;--field-radius:.5rem;--sidebar:#15242a;--sidebar-text:#f7faf5;--sidebar-muted:#a9b8b9;--sidebar-active:#304846;--sidebar-active-text:#e9ffdb;--success-ink:#39744b;--warning-ink:#94681d;--danger-ink:#a74739;--shadow-soft:0 8px 24px #1c3a2e0b;--sidebar-lime:#c8ee8b;--brand-border:#9db973;--sidebar-hover:#24383e;--sidebar-border:#314348;--topbar:rgba(255,255,255,.82);--heading-dot:#94bb69;--accent-hover:#29483f;--metric-neutral:#7d9680;--metric-mint-bg:#e7f2e9;--metric-mint:#58a879;--metric-blue-bg:#e7eff7;--metric-blue:#6494b4;--metric-amber-bg:#fbf0dc;--metric-amber:#c3a15f;--table-rule:#f0f2ef;--row-hover:#fafcf8}
.dark,[data-theme="dark"]{color-scheme:dark;--accent:#b7d6a0;--accent-foreground:#203426;--background:#14241d;--foreground:#e5ece1;--surface:#1c3026;--surface-foreground:var(--foreground);--surface-secondary:#22372c;--overlay:#263c30;--overlay-foreground:var(--foreground);--muted:#a6b7a9;--border:#354b3c;--default:#2b4133;--default-foreground:var(--foreground);--field-background:#17291f;--field-foreground:var(--foreground);--field-border:var(--border);--field-placeholder:#98aa9c;--sidebar:#111f25;--sidebar-text:#f7faf5;--sidebar-muted:#a9b8b9;--sidebar-active:#304846;--sidebar-active-text:#e9ffdb;--success-ink:#aed19b;--warning-ink:#e0c07a;--danger-ink:#eeaaa0;--shadow-soft:none;--topbar:#1c3026;--metric-neutral:#aec3a8;--metric-mint-bg:#294337;--metric-mint:#89caa1;--metric-blue-bg:#273f50;--metric-blue:#a2c4de;--metric-amber-bg:#443e2c;--metric-amber:#d7ba7a;--table-rule:#2f4336;--row-hover:#243a2d;--accent-hover:#c8e5b2}
`
export const PLATFORM_THEME_SCRIPT = `(()=>{
const key='dsh-phalanx.appearance.v1';let preference='system';
try{const saved=localStorage.getItem(key);if(['light','dark','system'].includes(saved))preference=saved}catch{}
const media=matchMedia('(prefers-color-scheme: dark)');
const apply=()=>{document.documentElement.dataset.appearance=preference;const theme=preference==='system'?(media.matches?'dark':'light'):preference;document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('dark',theme==='dark');document.documentElement.classList.toggle('light',theme==='light');document.querySelectorAll('select[data-appearance]').forEach(select=>{select.value=preference});dispatchEvent(new CustomEvent('dsh-phalanx:appearance',{detail:preference}))};
const choose=value=>{preference=['light','dark','system'].includes(value)?value:'system';try{localStorage.setItem(key,preference)}catch{}apply()};
window.dshPhalanxAppearance={get:()=>preference,set:choose};
document.addEventListener('change',event=>{if(event.target.matches('select[data-appearance]'))choose(event.target.value)});
addEventListener('storage',event=>{if(event.key===key){preference=['light','dark','system'].includes(event.newValue)?event.newValue:'system';apply()}});
media.addEventListener('change',apply);document.addEventListener('DOMContentLoaded',apply);apply();
})()`
