import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { chromium, type Browser } from 'playwright'
import { afterEach, expect, it } from 'vitest'
import { createCommunityApplication } from '../src/composition/community-application.js'
import { readBootstrapCredential } from '../src/adapters/bootstrap-credential.js'
import type { CommunityApplication } from '../src/ports/community-application.js'
let app: CommunityApplication | undefined, browser: Browser | undefined, root: string | undefined
afterEach(async () => { await browser?.close(); await app?.stop(); if (root) await rm(root, { recursive: true, force: true }) })
it('renders Chinese platform entries without admin assets and shares explicit language with the management framework', async () => {
 root = await mkdtemp(join(tmpdir(), 'community-language-'))
 app = createCommunityApplication({ listen: { host: '127.0.0.1', port: 0 }, sessionSecret: 'language-fixture-session-secret-at-least-32-bytes', runtime: { command: '/unavailable-dsh', args: [], dataRoot: root, defaultModel: { provider: 'deepseek-official', model: 'fixture', upstream: { baseUrl: 'https://api.deepseek.com' } } } })
 const origin = await app.start(); browser = await chromium.launch({ headless: true })
 const context = await browser.newContext({ locale: 'zh-TW' }); const page = await context.newPage(); page.setDefaultTimeout(10_000)
 await context.route('**/admin/assets/**', route => route.abort())
 const initial = await page.goto(`${origin}/login`)
 expect(await initial!.text()).toContain('<html lang="zh-CN">')
 await page.getByRole('heading', { name: '登录 dsh-phalanx', exact: true }).waitFor()
 await page.getByLabel('用户名', { exact: true }).fill('missing'); await page.getByLabel('密码', { exact: true }).fill('wrong')
 await page.getByRole('button', { name: '登录', exact: true }).click()
 await page.getByRole('alert').filter({ hasText: '用户名或密码错误。' }).waitFor()
 await page.goto(`${origin}/bootstrap#credential=${readBootstrapCredential(root)!.credential}`)
 await page.getByRole('heading', { name: '创建首个管理员', exact: true }).waitFor()
 await page.getByLabel('平台语言', { exact: true }).selectOption('en')
 await page.getByRole('heading', { name: 'Create the first administrator', exact: true }).waitFor()
 await page.getByLabel('Username', { exact: true }).fill('admin'); await page.getByLabel('Password', { exact: true }).fill('password')
 await page.getByRole('button', { name: 'Create administrator', exact: true }).click(); await page.waitForURL(`${origin}/admin`)
 await context.unroute('**/admin/assets/**'); await page.reload()
 await page.getByRole('heading', { name: 'Account management', exact: true }).waitFor()
 await page.getByRole('button', { name: /Platform language/ }).click(); await page.getByRole('option', { name: '简体中文', exact: true }).click()
 await page.getByRole('navigation', { name: '管理导航', exact: true }).waitFor()
 expect(await page.locator('html').getAttribute('lang')).toBe('zh-CN')
 await page.reload(); await page.getByRole('link', { name: '系统设置', exact: true }).click()
 await page.getByRole('heading', { name: '系统设置', exact: true }).waitFor()
 expect((await context.cookies()).find(cookie => cookie.name === 'dsh-phalanx.lang')?.value).toBe('zh-CN')
 await context.route('**/admin/assets/**', route => route.abort())
 await page.goto(`${origin}/recovery`)
 await page.getByRole('heading', { name: '实例恢复', exact: true }).waitFor()
 await page.getByRole('checkbox').check(); await page.getByRole('button', { name: '重启实例', exact: true }).click()
 await page.getByRole('status').filter({ hasText: '重启失败。' }).waitFor()
 expect(await page.locator('script[src]').count()).toBe(0)
 await page.getByRole('button', { name: '退出登录', exact: true }).click(); await page.waitForURL(`${origin}/login`)
 await page.getByRole('heading', { name: '登录 dsh-phalanx', exact: true }).waitFor()
 await page.getByLabel('平台语言', { exact: true }).selectOption('system')
 await page.getByRole('heading', { name: '登录 dsh-phalanx', exact: true }).waitFor()
 expect((await context.cookies()).find(cookie => cookie.name === 'dsh-phalanx.lang')?.value).toBe('system')
})
it('localizes account drafts, actions and known errors while retaining unknown server diagnostics', async () => {
 root = await mkdtemp(join(tmpdir(), 'community-account-language-'))
 app = createCommunityApplication({ listen: { host: '127.0.0.1', port: 0 }, sessionSecret: 'language-fixture-session-secret-at-least-32-bytes', runtime: { command: '/unavailable-dsh', args: [], dataRoot: root, defaultModel: { provider: 'deepseek-official', model: 'fixture', upstream: { baseUrl: 'https://api.deepseek.com' } } } })
 const origin = await app.start(); browser = await chromium.launch({ headless: true })
 const context = await browser.newContext({ locale: 'zh-CN' }); const page = await context.newPage(); page.setDefaultTimeout(5_000)
 await context.request.post(`${origin}/bootstrap`, { headers: { origin }, form: { credential: readBootstrapCredential(root)!.credential, username: 'admin', password: 'password' }, maxRedirects: 0 })
 await page.goto(`${origin}/admin`); await page.getByRole('button', { name: '添加账户', exact: true }).click()
 const drawer = page.getByRole('dialog', { name: '创建成员', exact: true })
 await drawer.getByLabel('用户名', { exact: true }).fill('member'); await drawer.getByLabel('邮箱', { exact: true }).fill('member@example.test'); await drawer.getByLabel('临时密码', { exact: true }).fill('password')
 await drawer.getByRole('button', { name: '创建账户', exact: true }).click(); await drawer.waitFor({ state: 'detached' })
 await page.getByRole('status').filter({ hasText: '已创建账户 member。' }).waitFor()
 await page.getByRole('button', { name: '编辑 member', exact: true }).click()
 const edit = page.getByRole('dialog', { name: '编辑账户：member', exact: true })
 await edit.getByLabel('邮箱', { exact: true }).fill('changed@example.test')
 await page.route('**/admin/api/accounts/member/actions', route => route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ code: 'email-in-use', error: 'Email is already in use' }) }))
 await edit.getByRole('button', { name: '保存邮箱', exact: true }).click(); await edit.getByRole('alert').filter({ hasText: '此邮箱已被使用。' }).waitFor()
 await page.unroute('**/admin/api/accounts/member/actions')
 await page.route('**/admin/api/accounts/member/actions', route => route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ code: 'new-server-code', error: 'Future English diagnostic' }) }))
 await edit.getByRole('button', { name: '保存邮箱', exact: true }).click(); await edit.getByRole('alert').filter({ hasText: 'Future English diagnostic' }).waitFor()
 expect(await edit.getByLabel('邮箱', { exact: true }).inputValue()).toBe('changed@example.test')
 await edit.getByRole('button', { name: '取消', exact: true }).click(); await page.getByRole('button', { name: '放弃更改', exact: true }).click()
 await page.getByRole('button', { name: 'member 的更多操作', exact: true }).click(); await page.getByRole('menuitem', { name: '重置 member 的 DSH 环境', exact: true }).click()
 await page.getByRole('dialog', { name: '重置 DSH 环境：member', exact: true }).waitFor()
 await page.getByRole('dialog', { name: '重置 DSH 环境：member', exact: true }).locator('[data-slot="checkbox-control"]').click()
 expect(await page.getByRole('checkbox', { name: '我已了解，正在运行的任务将中断。', exact: true }).isChecked()).toBe(true)
 await page.route('**/admin/api/accounts/member/reset-environment', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ username: 'member', spaceId: 'space', entry: '/app/space/', backup: { id: 'backup', location: '/private/backup', restoreInstructionsPath: '/private/backup/README.txt', restoreInstructions: 'Original instructions for an older client' } }) }))
 await page.getByRole('dialog', { name: '重置 DSH 环境：member', exact: true }).getByRole('button', { name: '重置环境', exact: true }).click()
 await page.getByRole('region', { name: '环境备份', exact: true }).getByText('请先停止平台服务和目标容器，再按 /private/backup/README.txt 中的说明恢复。备份将保留，直到部署者主动删除。', { exact: true }).waitFor()
 await page.getByRole('button', { name: /平台语言/ }).click(); await page.getByRole('option', { name: 'English', exact: true }).click()
 await page.getByRole('button', { name: 'Add account', exact: true }).waitFor()
})
