import { createServer } from 'node:http'
import { mkdtemp, mkdir, rm, stat, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { chromium } from 'playwright'
import { expect, it } from 'vitest'
import { createCommunityApplication } from '../src/composition/community-application.js'
import { readBootstrapCredential } from '../src/adapters/bootstrap-credential.js'
import { declaredRuntimeRevision } from '../src/adapters/runtime-revision.js'

it('configures write-only upstream credentials using HeroUI and retains Chinese and mobile layouts', async () => {
  const requests: { path: string, authorization: string, body: string }[] = []
  const upstream = createServer(async (req, res) => {
    let body = ''; for await (const chunk of req) body += chunk
    requests.push({ path: req.url!, authorization: req.headers.authorization!, body })
    res.end(`echo ${req.headers.authorization}`)
  })
  await new Promise<void>(resolve => upstream.listen(0, '127.0.0.1', resolve))
  const address = upstream.address(); if (!address || typeof address === 'string') throw Error('missing address')
  const upstreamUrl = `http://127.0.0.1:${address.port}`
  const root = await mkdtemp(join(tmpdir(), 'plugin-upstream-ui-'))
  const app = createCommunityApplication({ listen: { host: '127.0.0.1', port: 0 }, sessionSecret: 'plugin-upstream-ui-fixture-secret-value', runtime: { command: '/unavailable', args: [], dataRoot: root, defaultModel: { provider: 'deepseek-official', model: 'fixture', upstream: { baseUrl: 'https://example.test' } } } }, {
    pluginPreparer: { prepare: async input => ({ ...input, title: 'Shared plugin', description: '', artifact: 'artifacts/fixture', integrity: 'sha512-fixture', runtimeRevision: declaredRuntimeRevision(), bundlePatch: '- insert:\n  - id: main\n    name: plugin\n', dependencies: {} }) },
  })
  const browser = await chromium.launch({ headless: true })
  try {
    const origin = await app.start(); const page = await browser.newPage({ locale: 'en' }); page.setDefaultTimeout(15000)
    const cdp = await page.context().newCDPSession(page)
    if (process.env.DSH_PHALANX_E2E_CPU_THROTTLE) await cdp.send('Emulation.setCPUThrottlingRate', { rate: 4 })
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
    await page.goto(`${origin}/bootstrap#credential=${readBootstrapCredential(root)!.credential}`)
    await page.getByLabel('Username', { exact: true }).fill('admin'); await page.getByLabel('Password', { exact: true }).fill('password')
    await page.getByRole('button', { name: 'Create administrator' }).click(); await page.waitForURL(origin + '/admin')
    await page.request.post(origin + '/admin/api/plugins', { headers: { origin }, data: { action: 'add', packageName: 'plugin', version: '1.0.0' } })
    await page.getByRole('link', { name: 'Plugin library', exact: true }).click()
    await page.getByRole('button', { name: 'View plugin plugin', exact: true }).click()
    expect(await page.getByRole('dialog', { name: 'Shared plugin', exact: true }).evaluate(element => element.clientWidth)).toBe(800)
    await page.getByRole('button', { name: 'Add upstream', exact: true }).click()
    expect(await page.getByRole('dialog', { name: 'Add upstream', exact: true }).evaluate(element => element.clientWidth)).toBe(720)
    await page.getByLabel('Platform credential', { exact: true }).fill('fictional-write-only-key')
    await page.getByRole('tab', { name: 'Request headers', exact: true }).click()
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await page.getByRole('dialog', { name: 'Unsaved changes', exact: true }).getByRole('button', { name: 'Save changes', exact: true }).click()
    await expect.poll(() => page.getByRole('tab', { name: 'Basic information', exact: true }).getAttribute('aria-selected')).toBe('true')
    await page.getByRole('alert').waitFor()
    await page.getByLabel('Upstream name', { exact: true }).fill('search')
    await page.getByLabel('Upstream address', { exact: true }).fill(upstreamUrl + '/api')
    await page.getByLabel('Platform credential', { exact: true }).fill('fictional-write-only-key')
    await page.getByRole('tab', { name: 'Request headers', exact: true }).click()
    await page.getByLabel('Header name', { exact: true }).fill('')
    await page.getByRole('tab', { name: 'Basic information', exact: true }).click()
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await expect.poll(() => page.getByRole('tab', { name: 'Request headers', exact: true }).getAttribute('aria-selected')).toBe('true')
    await page.getByRole('alert').waitFor()
    await page.getByLabel('Header name', { exact: true }).fill('Authorization')
    await page.getByRole('tab', { name: 'Test request', exact: true }).click()
    await page.getByLabel('Test path', { exact: true }).fill('/check')
    await page.getByLabel('Test JSON body (optional)', { exact: true }).fill('{invalid')
    await page.getByRole('tab', { name: 'Basic information', exact: true }).click()
    expect(await page.getByLabel('Platform credential', { exact: true }).inputValue()).toBe('fictional-write-only-key')
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await expect.poll(() => page.getByRole('tab', { name: 'Test request', exact: true }).getAttribute('aria-selected')).toBe('true')
    await page.getByText('Enter a valid JSON test body.', { exact: true }).waitFor()
    await page.getByLabel('Test JSON body (optional)', { exact: true }).fill('{"query":"sample"}')
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await page.getByText('Credential configured', { exact: true }).waitFor()
    await page.getByRole('button', { name: 'Test saved request', exact: true }).click()
    await page.getByText('Upstream test passed', { exact: true }).waitFor()
    await page.getByText('echo Bearer ●●●●', { exact: true }).waitFor()
    expect(requests[0]).toEqual({ path: '/api/check', authorization: 'Bearer fictional-write-only-key', body: '{"query":"sample"}' })
    expect(await page.locator('body').innerText()).not.toContain('fictional-write-only-key')
    const api = origin + '/admin/api/plugins/upstreams?packageName=plugin'
    const saved = await (await page.request.get(api)).text()
    expect(saved).not.toContain('fictional-write-only-key'); expect(JSON.parse(saved)[0].hasCredential).toBe(true)
    expect((await stat(join(root, 'plugin-upstreams.json'))).mode & 0o777).toBe(0o600)
    await page.getByRole('button', { name: 'Edit upstream', exact: true }).click()
    expect(await page.getByLabel('Platform credential', { exact: true }).inputValue()).toBe('')
    await page.getByLabel('Upstream address', { exact: true }).fill(upstreamUrl + '/v2')
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    expect(await readFile(join(root, 'plugin-upstreams.json'), 'utf8')).toContain('fictional-write-only-key')
    await page.getByRole('button', { name: 'Edit upstream', exact: true }).click()
    await page.getByLabel('Platform credential', { exact: true }).fill('replacement-fictional-key')
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await page.getByRole('button', { name: 'Test saved request', exact: true }).click()
    await page.getByText('Upstream test passed', { exact: true }).waitFor()
    expect(requests.at(-1)).toMatchObject({ path: '/v2/check', authorization: 'Bearer replacement-fictional-key' })
    expect(await page.locator('body').innerText()).not.toContain('replacement-fictional-key')
    await page.getByRole('tab', { name: 'Publication', exact: true }).click()
    await page.getByRole('button', { name: 'Publish to marketplace', exact: true }).click()
    await page.getByRole('dialog', { name: 'Confirm publication', exact: true }).waitFor()
    await page.getByText('All members will use the platform credentials.', { exact: true }).waitFor()
    await page.getByRole('button', { name: 'Confirm', exact: true }).click()
    await page.getByRole('tab', { name: 'Access settings', exact: true }).click()
    const accessPanel = page.getByRole('region', { name: 'Access templates', exact: true })
    await accessPanel.getByRole('button', { name: 'Add variable', exact: true }).click()
    await page.getByLabel('Environment name', { exact: true }).fill('HOME')
    await page.getByLabel('Environment value', { exact: true }).fill('{access-token}')
    await page.getByRole('tab', { name: 'Version management', exact: true }).click()
    expect(await page.getByLabel('Environment name', { exact: true }).isVisible()).toBe(false)
    await page.getByRole('tab', { name: 'Access settings', exact: true }).click()
    expect(await page.getByLabel('Environment name', { exact: true }).inputValue()).toBe('HOME')
    await page.getByRole('tab', { name: 'Publication', exact: true }).click()
    await page.getByRole('button', { name: 'Close plugin details', exact: true }).click()
    await page.getByRole('dialog', { name: 'Unsaved changes', exact: true }).waitFor()
    await page.getByRole('dialog', { name: 'Unsaved changes', exact: true }).getByRole('button', { name: 'Save changes', exact: true }).click()
    await expect.poll(() => page.getByRole('tab', { name: 'Access settings', exact: true }).getAttribute('aria-selected')).toBe('true')
    await accessPanel.getByRole('alert').waitFor()
    await page.getByLabel('Environment name', { exact: true }).fill('ANYSEARCH_API_KEY')
    await page.getByLabel('Entry configuration YAML', { exact: true }).fill('main:\n  baseURL: "{upstream:search}"\n')
    await page.getByRole('button', { name: 'Save access settings', exact: true }).click()
    await page.getByText('Access saved. Affected members must restart their instances.', { exact: true }).waitFor()
    expect((await page.request.post(api, { headers: { origin }, data: { action: 'delete', name: 'search' } })).status()).toBe(409)
    await page.getByRole('button', { name: 'Remove variable', exact: true }).click()
    await page.getByLabel('Entry configuration YAML', { exact: true }).fill('')
    await page.getByRole('button', { name: 'Save access settings', exact: true }).click()
    await accessPanel.getByText('Access not configured', { exact: true }).waitFor()
    await page.getByRole('button', { name: 'Edit upstream', exact: true }).click()
    await page.getByRole('button', { name: 'Clear saved credential', exact: true }).click()
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await page.getByText('Credential not configured', { exact: true }).waitFor()
    expect(await readFile(join(root, 'plugin-upstreams.json'), 'utf8')).not.toContain('fictional-write-only-key')
    await page.getByRole('button', { name: 'Close plugin details', exact: true }).click()
    await page.getByRole('button', { name: /Platform language/ }).click(); await page.getByRole('option', { name: '简体中文', exact: true }).click()
    await page.getByRole('option', { name: '简体中文', exact: true }).waitFor({ state: 'detached' })
    await page.getByRole('button', { name: '查看插件 plugin', exact: true }).click()
    await page.getByLabel('条目配置 YAML', { exact: true }).waitFor()
    await page.setViewportSize({ width: 390, height: 844 })
    const mobileDrawer = page.getByRole('dialog', { name: 'Shared plugin', exact: true })
    expect(await mobileDrawer.evaluate(element => element.clientWidth)).toBe(390)
    expect(await mobileDrawer.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    await page.getByRole('tab', { name: '发布管理', exact: true }).click()
    await page.getByRole('button', { name: '取消发布', exact: true }).waitFor()
    await page.getByRole('tab', { name: '版本维护', exact: true }).click()
    await page.getByRole('button', { name: '更换 npm 版本', exact: true }).waitFor()
    await page.getByRole('tab', { name: '接入配置', exact: true }).click()
    await page.getByRole('button', { name: '编辑上游', exact: true }).click()
    await page.getByLabel('平台凭据', { exact: true }).waitFor()
    const mobileEditor = page.getByRole('dialog', { name: '编辑上游', exact: true })
    expect(await mobileEditor.evaluate(element => element.scrollWidth <= element.clientWidth && element.clientWidth <= innerWidth)).toBe(true)
    for (const name of ['请求头', '测试请求', '基本信息']) {
      await page.getByRole('tab', { name, exact: true }).click()
      expect(await mobileEditor.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const evidence = process.env.DSH_PHALANX_E2E_EVIDENCE_DIR
    if (evidence) { await mkdir(evidence, { recursive: true }); await page.screenshot({ path: join(evidence, 'upstream-editor-zh.png'), fullPage: true, animations: 'disabled' }) }
    await page.getByRole('button', { name: '删除上游', exact: true }).click()
    await page.getByRole('button', { name: '确认', exact: true }).click()
    expect(await (await page.request.get(api)).json()).toEqual([])
    await cdp.send('Emulation.setCPUThrottlingRate', { rate: 1 })
    expect(errors).toEqual([])
  } finally { await browser.close(); await app.stop(); await new Promise<void>(resolve => upstream.close(() => resolve())); await rm(root, { recursive: true, force: true }) }
})
