/** Login presentation is delivered inline, independently of restricted admin assets. */
export const LOGIN_INTRODUCTION = `<aside class="login-introduction"><div class="login-wordmark"><span class="login-brand-mark" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m12 3 9 5-9 5-9-5 9-5ZM3 12l9 5 9-5M3 16l9 5 9-5"/></svg></span><div>dsh-phalanx<small>COMMUNITY EDITION</small></div></div><div class="login-story"><p class="entry-eyebrow">A SPACE OF YOUR OWN</p><h2>Your space.<br>Your tools.</h2><p>A private DSH workspace for every teammate.<br>One platform, on your infrastructure.</p><div class="space-art" aria-hidden="true"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div></div><p class="login-intro-footer">Built for teams. Hosted by you.</p></aside>`
export const LOGIN_PAGE_CSS = `
body.login-page{padding:0;min-height:100dvh;display:grid;grid-template-columns:minmax(360px,43%) 1fr;font-family:system-ui,sans-serif}
.login-introduction{background:var(--sidebar);color:var(--sidebar-text);padding:44px clamp(32px,5vw,80px);display:flex;flex-direction:column;min-height:100dvh}
.login-wordmark{display:flex;align-items:center;gap:12px;font-size:21px;font-weight:650;letter-spacing:-.04em}.login-wordmark small{display:block;font-size:10px;font-weight:400;letter-spacing:.16em;color:var(--sidebar-muted);margin-top:3px}.login-brand-mark{width:38px;height:42px;border-radius:8px;background:var(--sidebar-active);color:var(--sidebar-active-text);display:grid;place-items:center}.login-brand-mark svg{width:25px;height:25px}
.login-story{margin:auto 0;padding:70px 0 40px}.login-page .login-story .entry-eyebrow{color:var(--sidebar-muted);font-size:10px;letter-spacing:.16em}.login-story h2{font-size:clamp(44px,5vw,68px);font-weight:500;line-height:1.1;letter-spacing:-.055em;margin:20px 0 24px}.login-story>p:not(.entry-eyebrow){font-size:13px;line-height:1.9;color:var(--sidebar-muted)}
.space-art{display:grid;grid-template-columns:repeat(3,46px);gap:10px;margin-top:40px;transform:skewY(-8deg);width:fit-content}.space-art span{width:46px;height:46px;border:1px solid #cfdfbe35;border-radius:7px;background:#cfdfbe08}.space-art span:nth-child(5){background:var(--sidebar-active);border-color:var(--sidebar-active)}.space-art span:nth-child(3),.space-art span:nth-child(7){opacity:.3}.login-intro-footer{font-size:11px;color:var(--sidebar-muted);margin:0}
.login-page main{align-self:center;width:calc(100% - 64px);max-width:392px;background:transparent;border:0;border-radius:0;box-shadow:none;padding:48px 0;margin:0 auto}.login-page main>.brand{display:none}.login-page .entry-eyebrow{font-size:10px;letter-spacing:.14em;font-weight:600;color:var(--muted);margin:0 0 16px}.login-page h1{font-size:28px;line-height:1.25;letter-spacing:-.045em;margin:0 0 12px}.login-page main>p{font-size:13px;line-height:1.7}.login-page form{margin-top:30px}.login-page label{font-size:12px;font-weight:550;margin:22px 0}.login-page input{height:46px;border-radius:7px;padding:10px 12px;font-size:15px}.login-page input:focus{border-color:var(--accent)}.login-page button{width:100%;display:flex;align-items:center;justify-content:space-between;border-radius:7px;font-size:13px;height:44px;margin-top:28px}.login-page .login-help{font-size:12px;color:var(--muted);margin:20px 0 0}.login-page .appearance{border-top:1px solid var(--border);padding-top:22px;margin-top:30px;font-size:11px;font-weight:400}.login-page .appearance select{font-size:11px;padding:6px 10px;border-radius:6px;min-width:105px;background:var(--surface)}.login-page .entry-error{background:var(--surface);color:var(--danger-ink);border-color:color-mix(in srgb,var(--danger-ink) 30%,var(--border));font-size:12px}
@media(max-width:760px){body.login-page{display:flex;flex-direction:column}.login-introduction{min-height:0;padding:23px 24px}.login-wordmark{font-size:18px}.login-wordmark small{font-size:9px}.login-story,.login-intro-footer{display:none}.login-page main{width:calc(100% - 48px);padding:42px 0;flex:1}.login-page h1{font-size:26px}}
`
